name: Cypress tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # have the ability to trigger this workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Cypress tests
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: add prod to hosts file
      run: echo 127.0.0.1 prod.foo.redhat.com | sudo tee -a /etc/hosts 
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.5.1'
        
    - name: Install dependencies
      run: npm ci

    - name: Cypress run
      uses: cypress-io/github-action@v6
      env:
        DEBUG: 'cypress:*'
      with:
        start: npm run start:prod:beta
        browser: chrome
        record: true
        config: env={passwordAdmin=${{ secrets.LIGHTSPEED_ORG_ADMIN_PASSWORD }}, passwordUser=${{ secrets.LIGHTSPEED_TEST_USER_PASSWORD }}}
        config-file: cypress-github.config.ts
    
    - name: Upload Cypress screenshots test results
      uses: actions/upload-artifact@v3
      with:
        name: cypress-screenshots-results
        path: cypress/screenshots
      if: ${{ always() }}
    
    - name: Upload Cypress videos test results
      uses: actions/upload-artifact@v3
      with:
        name: cypress-videos-results
        path: cypress/videos
      if: ${{ always() }}
