name: Cypress tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # have the ability to trigger this workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Cypress tests
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: add prod to hosts file
      run: echo 127.0.0.1 prod.foo.redhat.com | sudo tee -a /etc/hosts 
    
    - name: Install root dependencies
      uses: bahmutov/npm-install@v1

    - name: Start server in the background
      run: npm run start:prod:beta &

    - name: Sleep for 60 seconds
      run: sleep 60s
      shell: bash

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        record: true
        config: env={passwordAdmin=${{ secrets.LIGHTSPEED_ORG_ADMIN_PASSWORD }}, passwordUser=${{ secrets.LIGHTSPEED_TEST_USER_PASSWORD }}}
        config-file: cypress-github.config.ts
    
    - name: Upload Cypress screenshots test results
      uses: actions/upload-artifact@v3
      with:
        name: cypress-screenshots-results
        path: cypress/screenshots
      if: ${{ always() }}
    
    - name: Upload Cypress videos test results
      uses: actions/upload-artifact@v3
      with:
        name: cypress-videos-results
        path: cypress/videos
      if: ${{ always() }}
